schema_version = 1
target_sha256 = "56350024879199861579c11b0e1c67b9590e10a8d40cd5996b109deec9afca7e"
compiler_sha256 = "71c93ca5bddc9b2816d0e053cac2b952f926f6b9321fab6b1ab6e8603621324c"
source = "src/battle/EventEffectStateRuntime.cpp"
enable_gs = false
min_nonreloc_coverage = 0.70
min_nonreloc_bytes = 24
max_alignment_tail = 0
alignment_tail_hex = ""

[[anchors]]
address = "0x004698E0"
size = 114
symbol = "?find@?$_Tree@V?$_Tmap_traits@CV?$vector@EV?$allocator@E@std@@@std@@U?$less@C@2@V?$allocator@U?$pair@$$CBCV?$vector@EV?$allocator@E@std@@@std@@@std@@@2@$0A@@std@@@std@@QAE?AViterator@12@ABC@Z"

[[anchors]]
address = "0x00449A80"
size = 343
symbol = "?_Growmap@?$deque@UBackgroundRenderEntry@th105@@V?$allocator@UBackgroundRenderEntry@th105@@@std@@@std@@IAEXI@Z"

[[anchors]]
address = "0x00449D70"
size = 121
symbol = "?push_back@?$deque@UBackgroundRenderEntry@th105@@V?$allocator@UBackgroundRenderEntry@th105@@@std@@@std@@QAEXABUBackgroundRenderEntry@th105@@@Z"

[[anchors]]
address = "0x004371C0"
size = 80
symbol = "?_Erase@?$_Tree@V?$_Tmap_traits@CV?$vector@EV?$allocator@E@std@@@std@@U?$less@C@2@V?$allocator@U?$pair@$$CBCV?$vector@EV?$allocator@E@std@@@std@@@std@@@2@$0A@@std@@@std@@IAEXPAU_Node@?$_Tree_nod@V?$_Tmap_traits@CV?$vector@EV?$allocator@E@std@@@std@@U?$less@C@2@V?$allocator@U?$pair@$$CBCV?$vector@EV?$allocator@E@std@@@std@@@std@@@2@$0A@@std@@@2@@Z"
