schema_version = 1
target_sha256 = "56350024879199861579c11b0e1c67b9590e10a8d40cd5996b109deec9afca7e"
compiler_sha256 = "71c93ca5bddc9b2816d0e053cac2b952f926f6b9321fab6b1ab6e8603621324c"
source = "src/ui/SceneRenderClusterConstructor.cpp"
enable_gs = true
min_nonreloc_coverage = 0.70
min_nonreloc_bytes = 24
max_alignment_tail = 0
alignment_tail_hex = ""

[[anchors]]
address = "0x0041EB30"
size = 29
symbol = "?_Buynode@?$list@USceneListRecord124@th105@@V?$allocator@USceneListRecord124@th105@@@std@@@std@@IAEPAU_Node@?$_List_nod@USceneListRecord124@th105@@V?$allocator@USceneListRecord124@th105@@@std@@@2@XZ"

[[anchors]]
address = "0x0041EB90"
size = 55
symbol = "?_Buynode@?$_Tree@V?$_Tmap_traits@HUSceneMapValue20@th105@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHUSceneMapValue20@th105@@@std@@@4@$0A@@std@@@std@@IAEPAU_Node@?$_Tree_nod@V?$_Tmap_traits@HUSceneMapValue20@th105@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHUSceneMapValue20@th105@@@std@@@4@$0A@@std@@@2@XZ"

[[anchors]]
address = "0x0041ECF0"
size = 695
symbol = "?erase@?$_Tree@V?$_Tmap_traits@HUSceneMapValue20@th105@@U?$less@H@std@@V?$allocator@U?$pair@$$CBHUSceneMapValue20@th105@@@std@@@4@$0A@@std@@@std@@QAE?AViterator@12@V312@@Z"
