schema_version = 1
target_sha256 = "56350024879199861579c11b0e1c67b9590e10a8d40cd5996b109deec9afca7e"
compiler_sha256 = "71c93ca5bddc9b2816d0e053cac2b952f926f6b9321fab6b1ab6e8603621324c"
source = "scripts/probes/fighter_sequence_deque_generated.cpp"
enable_gs = false
min_nonreloc_coverage = 0.70
min_nonreloc_bytes = 24

[[anchors]]
address = "0x0045D390"
size = 186
symbol = "??$_Copy_backward_opt@V?$_Deque_iterator@UFighterSequenceSlotGenerated@th105@@V?$allocator@UFighterSequenceSlotGenerated@th105@@@std@@$0A@@std@@V12@Uforward_iterator_tag@2@@std@@YA?AV?$_Deque_iterator@UFighterSequenceSlotGenerated@th105@@V?$allocator@UFighterSequenceSlotGenerated@th105@@@std@@$0A@@0@V10@00Uforward_iterator_tag@0@U_Nonscalar_ptr_iterator_tag@0@U_Range_checked_iterator_tag@0@@Z"

[[anchors]]
address = "0x0045D450"
size = 186
symbol = "??$_Copy_opt@V?$_Deque_iterator@UFighterSequenceSlotGenerated@th105@@V?$allocator@UFighterSequenceSlotGenerated@th105@@@std@@$0A@@std@@V12@Uforward_iterator_tag@2@@std@@YA?AV?$_Deque_iterator@UFighterSequenceSlotGenerated@th105@@V?$allocator@UFighterSequenceSlotGenerated@th105@@@std@@$0A@@0@V10@00Uforward_iterator_tag@0@U_Nonscalar_ptr_iterator_tag@0@U_Range_checked_iterator_tag@0@@Z"

[[anchors]]
address = "0x0045DA40"
size = 341
symbol = "?_Growmap@?$deque@UFighterSequenceSlotGenerated@th105@@V?$allocator@UFighterSequenceSlotGenerated@th105@@@std@@@std@@IAEXI@Z"
