#!/usr/bin/env python3
"""Generate the conservative TH105 reconstruction progress snapshot."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
OUTPUT = ROOT / "docs" / "PROGRESS.md"


def csv_rows(name: str) -> list[dict[str, str]]:
    with (CONFIG / name).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def render() -> str:
    functions = csv_rows("functions.csv")
    origins = {row["address"]: row for row in csv_rows("function-origins.csv")}
    matches = csv_rows("matches.csv")
    with (CONFIG / "implemented.csv").open(newline="", encoding="utf-8") as stream:
        implemented = [row[0] for row in csv.reader(stream) if row]
    authored = [
        row for row in functions if origins[row["address"]]["disposition"] == "authored"
    ]
    excluded = [
        row for row in functions if origins[row["address"]]["disposition"] == "exclude"
    ]
    review = len(functions) - len(authored) - len(excluded)
    exact_bytes = sum(int(row["size"], 0) for row in matches)
    return f"""# TH10.5 reconstruction progress

Generated by `python3 scripts/progress.py`. IDA candidate sizes are provisional
until each boundary is reconciled with target control flow.

| Measure | Count |
| --- | ---: |
| IDA 1.06a function candidates | {len(functions):,} |
| Origin/boundary review pending | {review:,} |
| Confirmed authored functions | {len(authored):,} |
| Classified exclusions | {len(excluded):,} |
| Source-present authored mappings | {len(implemented):,} |
| Canonical exact functions | {len(matches):,} |
| Canonical exact authored bytes | {exact_bytes:,} |

The former 1.06 reconstruction state is intentionally excluded. Exact totals
remain zero until a 1.06a VC8 object passes the canonical comparator and is
recorded in both `config/matches.csv` and `config/functions.csv`.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("error: docs/PROGRESS.md is stale; run python3 scripts/progress.py")
            return 1
        print("progress snapshot is current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
